#!/bin/bash

# /etc/network/if-post-down.d/dhcpcd-sync
#
# Hook script provided by the 'tkl-dhcpcd-ifupdown-glue' package and part of
# TurnKey GNU/Linux network configuration.
#
# Removes denyinterfaces entry when interface is deconfigured.
# This ensures dhcp works again if the interface is later reconfigured to dhcp
# without an ifup cycle (e.g. manual dhcpcd invocation).

update_dhcpcd_conf=/usr/lib/dhcpcd-ifupdown-glue/update-dhcpcd-conf

_info() {
    logger --tag=dhcpcd-ifupdown-glue "$*"
}

_warn() {
    logger --tag=dhcpcd-ifupdown-glue --priority warning "$*"
}

_info "if-post-down hook running for iface: $IFACE"

if [[ "$IFACE" == "lo" ]]; then
    _info "nothing to do for 'lo'"
    exit 0
elif [[ -z "$IFACE" ]]; then
    _warn "IFACE is empty - refusing to touch dhcpcd.conf"
    exit 0
elif [[ "$IFACE" == "--all" ]]; then
    # read all eth, wifi and bridge interfaces from interfaces file
    mapfile -t ifaces \
        <<<"$(awk '/^iface [ewb]/ {print $2}' /etc/network/interfaces | uniq)"
else
    ifaces=("$IFACE")
fi

for _ipv in ipv4 ipv6; do
    for iface in "${ifaces[@]}"; do
        $update_dhcpcd_conf remove-deny-dhcp "$iface" $_ipv
    done
done

_info "if-post-down hook finished for iface/s: ${ifaces[*]}"

exit 0
